# Generated by Django 4.2.9 on 2024-01-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.CharField(db_column='role', max_length=20),
        ),
    ]
